[package]
name = "sush"
version = "1.0.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.29.0", features = ["fs", "process", "signal", "term", "user", "time", "hostname", "resource"]}
termion = "4.0.3"
unicode-width = "0.1.11"
signal-hook = "0.3.17"
rev_lines = "0.3.0"
faccess = "0.2.4"
regex = "1.11.1"
rand = "0.8"
rand_chacha = "0.3"
time = "0.3"
sprintf = "0.4"
