[package]
name = "sush"
version = "1.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.29.0", features = ["fs", "process", "signal", "term", "user", "time", "hostname", "resource"]}
termion = "4.0.3"
unicode-width = "0.1.11"
signal-hook = "0.3.17"
rev_lines = "0.3.0"
faccess = "0.2.4"
io-streams = "0.16.3"
regex = "1.11.1"
rand = "0.9"
rand_chacha = { version = "0.9.0", features = [ "os_rng" ]}
time = "0.3"
sprintf = "0.4"

#Internationalization
fluent-bundle = "0.16"
unic-langid = "0.9"
once_cell = "1"
locale_config = "0.3"
widestring = "1.2.0"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
