name: macos-latest

on:
  push:
    branches: [ main, alpha, beta, sd/* ]
    paths: ['src/**', 'test/**', '!README.md' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Bash tests
      run: |
        dir=$PWD
        git clone https://github.com/shellgei/rusty_bash_test
        git checkout -b main refs/tags/v1.1.4
        cd rusty_bash_test
        ./test.bash $dir
